import type { Theme } from "./defaultTheme";

/**
 * Converts a Theme object into a :root CSS variables block.
 * No conditional logic — pure data-to-string mapping.
 */
export function generateCSSVariables(theme: Theme): string {
  const lines: string[] = [
    "/* Auto-generated by @website-builder/theme — do not edit */",
    ":root {",
    `  /* Colors */`,
    `  --color-primary: ${theme.colors.primary};`,
    `  --color-primary-fg: ${theme.colors.primaryFg};`,
    `  --color-secondary: ${theme.colors.secondary};`,
    `  --color-secondary-fg: ${theme.colors.secondaryFg};`,
    `  --color-background: ${theme.colors.background};`,
    `  --color-surface: ${theme.colors.surface};`,
    `  --color-text: ${theme.colors.text};`,
    `  --color-muted: ${theme.colors.textMuted};`,
    `  --color-border: ${theme.colors.border};`,
    `  --color-error: ${theme.colors.error};`,
    `  --color-success: ${theme.colors.success};`,
    `  --color-warning: ${theme.colors.warning};`,
    "",
    `  /* Typography */`,
    `  --font-family: ${theme.typography.fontFamily};`,
    `  --font-family-mono: ${theme.typography.fontFamilyMono};`,
    `  --font-size-base: ${theme.typography.fontSizeBase};`,
    `  --font-size-sm: ${theme.typography.fontSizeSm};`,
    `  --font-size-lg: ${theme.typography.fontSizeLg};`,
    `  --font-size-xl: ${theme.typography.fontSizeXl};`,
    `  --font-size-xxl: ${theme.typography.fontSizeXxl};`,
    `  --font-weight-regular: ${theme.typography.fontWeightRegular};`,
    `  --font-weight-medium: ${theme.typography.fontWeightMedium};`,
    `  --font-weight-bold: ${theme.typography.fontWeightBold};`,
    `  --line-height-base: ${theme.typography.lineHeightBase};`,
    `  --line-height-tight: ${theme.typography.lineHeightTight};`,
    "",
    `  /* Spacing */`,
    `  --spacing-xs: ${theme.spacing.xs};`,
    `  --spacing-sm: ${theme.spacing.sm};`,
    `  --spacing-md: ${theme.spacing.md};`,
    `  --spacing-lg: ${theme.spacing.lg};`,
    `  --spacing-xl: ${theme.spacing.xl};`,
    `  --spacing-xxl: ${theme.spacing.xxl};`,
    "",
    `  /* Border radius */`,
    `  --radius-sm: ${theme.border.radiusSm};`,
    `  --radius-md: ${theme.border.radiusMd};`,
    `  --radius-lg: ${theme.border.radiusLg};`,
    `  --radius-xl: ${theme.border.radiusXl};`,
    `  --radius-full: ${theme.border.radiusFull};`,
    "",
    `  /* Shadows */`,
    `  --shadow-sm: ${theme.shadow.sm};`,
    `  --shadow-md: ${theme.shadow.md};`,
    `  --shadow-lg: ${theme.shadow.lg};`,
    `  --shadow-xl: ${theme.shadow.xl};`,
    "}",
  ];

  return lines.join("\n");
}
