import type { ZodTypeAny } from "zod";
import {
  aboutSchema,
  contactSchema,
  faqSchema,
  featuresSchema,
  footerSchema,
  headerSchema,
  heroSchema,
  testimonialSchema,
  brandsSchema,
  pricingSchema,
  ctaSchema,
} from "@website-builder/sections/schemas";
import {
  blitzHeaderSchema,
  blitzHeroSchema,
  blitzBrandsSchema,
  blitzFeaturesSchema,
  blitzUseCasesSchema,
  blitzIntegrationsSchema,
  blitzPricingSchema,
  blitzPricingPlansSchema,
  blitzFAQSchema,
  blitzCTASchema,
  blitzFooterSchema,
} from "@website-builder/sections/schemas";
import {
  webCohortHeaderSchema,
  webCohortHeroSchema,
  webCohortBenefitsSchema,
  webCohortCurriculumSchema,
  webCohortWhyUsSchema,
  webCohortSpeakersSchema,
  webCohortNoteSchema,
  webCohortTestimonialsSchema,
  webCohortFAQSchema,
  webCohortFooterSchema,
  webCohortWhatsAppFloatSchema,
} from "@website-builder/sections/schemas";

// ─── Template preset definitions ─────────────────────────────────────────────
// These define the exact ordered section sequence for each template.
// The builder uses these for "one-click" template loading.
export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  thumbnail: string;
  accentColor: string;
  sectionSequence: string[]; // ordered list of registry keys
}

export const TEMPLATE_PRESETS: TemplateDefinition[] = [
  {
    id: "authantimate",
    name: "Authantimate",
    description: "A polished SaaS landing page with Tailwind CSS, animated sections, FAQ, testimonials, and a contact form.",
    thumbnail: "",
    accentColor: "#006BFF",
    sectionSequence: [
      "auth-header",
      "auth-hero",
      "auth-brands",
      "auth-features",
      "auth-about",
      "auth-cta",
      "auth-faq",
      "auth-testimonial",
      "auth-pricing",
      "auth-contact",
      "auth-footer",
    ],
  },
  {
    id: "blitz-clone",
    name: "Blitz Clone",
    description: "High-performance API-first SaaS landing page with staggered animations, interactive charts, and minimalist design.",
    thumbnail: "",
    accentColor: "#2563eb",
    sectionSequence: [
      "blitz-header",
      "blitz-hero",
      "blitz-brands",
      "blitz-features",
      "blitz-use-cases",
      "blitz-integrations",
      "blitz-pricing",
      "blitz-pricing-plans",
      "blitz-faq",
      "blitz-cta",
      "blitz-footer",
    ],
  },
  {
    id: "web-cohort",
    name: "Web-Cohort",
    description: "High-fidelity educational cohort landing page with premium dark aesthetics, interactive curriculum, and mentor showcases.",
    thumbnail: "",
    accentColor: "#CB97FF",
    sectionSequence: [
      "cohort-header",
      "cohort-hero",
      "cohort-benefits",
      "cohort-curriculum",
      "cohort-speakers",
      "cohort-why-us",
      "cohort-note",
      "cohort-testimonials",
      "cohort-faq",
      "cohort-footer",
      "cohort-whatsapp",
    ],
  },
];

export type TemplatePreset =
  | "core"
  | "authantimate"
  | "blitz-clone"
  | "web-cohort";
export type SectionFamily =
  | "header"
  | "hero"
  | "features"
  | "testimonials"
  | "footer"
  | "about"
  | "faq"
  | "contact";

export interface RegistryEntry {
  component: string;
  importPath: string;
  schema: ZodTypeAny;
  displayName: string;
  description: string;
  category: "layout" | "content" | "social" | "conversion" | "support";
  defaultProps: Record<string, unknown>;
  family: SectionFamily;
  template: TemplatePreset;
  previewBackground: string;
  previewAccent?: string;
}

export const registry: Record<string, RegistryEntry> = {
  "header-1": {
    component: "Header",
    importPath: "@/sections/header/Header",
    schema: headerSchema,
    displayName: "Header / Navigation (Classic)",
    description: "Sticky top navigation bar with brand name and CTA.",
    category: "layout",
    family: "header",
    template: "core",
    previewBackground: "linear-gradient(135deg, #1f2937, #111827)",
    previewAccent: "#6366f1",
    defaultProps: {
      title: "My Brand",
      showCTA: true,
      ctaText: "Get Started",
      ctaHref: "#",
      variant: "light",
      layout: "classic",
      navLinks: [
        { label: "Home", href: "#" },
        { label: "Features", href: "#" },
        { label: "Pricing", href: "#" },
      ],
    },
  },
  "header-2": {
    component: "Header",
    importPath: "@/sections/header/Header",
    schema: headerSchema,
    displayName: "Header / Auth Minimal",
    description: "Authentimate-style clean header with centered links.",
    category: "layout",
    family: "header",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #f8fafc, #eef2ff)",
    previewAccent: "#4f46e5",
    defaultProps: {
      title: "AuthentiMATE",
      subtitle: "Creative Cohort",
      showCTA: true,
      ctaText: "Get Pro",
      ctaHref: "#",
      variant: "light",
      layout: "auth-minimal",
      navLinks: [
        { label: "Home", href: "#" },
        { label: "Features", href: "#" },
        { label: "Pages", href: "#" },
        { label: "Support", href: "#" },
      ],
    },
  },
  "header-3": {
    component: "Header",
    importPath: "@/sections/header/Header",
    schema: headerSchema,
    displayName: "Header / Glass Dark",
    description: "Dark, high-contrast floating header card.",
    category: "layout",
    family: "header",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #0f172a, #1e1b4b)",
    previewAccent: "#a78bfa",
    defaultProps: {
      title: "AuthentiMATE",
      subtitle: "Premium cohort",
      showCTA: true,
      ctaText: "Apply Now",
      ctaHref: "#",
      variant: "dark",
      layout: "auth-glass",
      navLinks: [
        { label: "Home", href: "#" },
        { label: "Tracks", href: "#" },
        { label: "Projects", href: "#" },
      ],
    },
  },
  "hero-1": {
    component: "Hero",
    importPath: "@/sections/hero/Hero",
    schema: heroSchema,
    displayName: "Hero / Classic",
    description: "Full-width hero with headline, description, and CTA buttons.",
    category: "conversion",
    family: "hero",
    template: "core",
    previewBackground: "linear-gradient(135deg, #4338ca, #7c3aed)",
    previewAccent: "#ffffff",
    defaultProps: {
      headline: "Build Something Amazing",
      description: "The fastest way to launch your next product.",
      primaryCTAText: "Get Started",
      primaryCTAHref: "#",
      secondaryCTAText: "Learn More",
      secondaryCTAHref: "#",
      backgroundStyle: "gradient",
      align: "center",
      layout: "classic",
    },
  },
  "hero-2": {
    component: "Hero",
    importPath: "@/sections/hero/Hero",
    schema: heroSchema,
    displayName: "Hero / AuthentiMATE",
    description:
      "Template-inspired hero with email capture and product visual.",
    category: "conversion",
    family: "hero",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e0e7ff)",
    previewAccent: "#111827",
    defaultProps: {
      kicker: "🔥 Certify Smarter, Not Harder",
      headline: "Digital Certificates Made Easy",
      description:
        "Say goodbye to manual workflows. Generate, share, and verify credentials in minutes.",
      primaryCTAText: "Get Early Access",
      primaryCTAHref: "#",
      secondaryCTAText: "View Demo",
      secondaryCTAHref: "#",
      imageUrl: "",
      emailPlaceholder: "Enter your email address",
      backgroundStyle: "solid",
      align: "left",
      layout: "authantimate",
    },
  },
  "hero-3": {
    component: "Hero",
    importPath: "@/sections/hero/Hero",
    schema: heroSchema,
    displayName: "Hero / Split Card",
    description: "Two-panel hero with a premium CTA content card.",
    category: "conversion",
    family: "hero",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #1d4ed8, #312e81)",
    previewAccent: "#ffffff",
    defaultProps: {
      kicker: "Built for serious builders",
      headline: "Ship polished pages faster than ever",
      description:
        "Drag, customize, and generate production-ready code with template-accurate styles.",
      primaryCTAText: "Start Building",
      primaryCTAHref: "#",
      secondaryCTAText: "See Templates",
      secondaryCTAHref: "#",
      backgroundStyle: "gradient",
      align: "left",
      layout: "split-card",
    },
  },
  "features-1": {
    component: "Features",
    importPath: "@/sections/features/Features",
    schema: featuresSchema,
    displayName: "Features / Grid",
    description: "Showcase product capabilities in a responsive card grid.",
    category: "content",
    family: "features",
    template: "core",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    previewAccent: "#334155",
    defaultProps: {
      heading: "Why Choose Us",
      subheading: "Everything you need to build, launch, and grow.",
      features: [
        {
          title: "Fast",
          description: "Blazing fast performance out of the box.",
        },
        {
          title: "Secure",
          description: "Enterprise-grade security by default.",
        },
        { title: "Scalable", description: "Grows with your business needs." },
      ],
      columns: "3",
      variant: "light",
      layout: "cards",
    },
  },
  "features-2": {
    component: "Features",
    importPath: "@/sections/features/Features",
    schema: featuresSchema,
    displayName: "Features / Auth Grid",
    description:
      "Authentimate-style boxed layout with stronger visual contrast.",
    category: "content",
    family: "features",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #eef2ff, #ede9fe)",
    previewAccent: "#4f46e5",
    defaultProps: {
      kicker: "SOLID FEATURES",
      heading: "What Sets Us Apart",
      subheading:
        "From creation to verification, everything is streamlined for modern teams.",
      features: [
        {
          title: "Template Variants",
          description:
            "Multiple hero, header, and section styles in one builder.",
        },
        {
          title: "Live Preview",
          description: "Instantly visualize output before generation.",
        },
        {
          title: "Clean Export",
          description: "Generate only selected sections for lean output.",
        },
        {
          title: "AI Copy Assist",
          description: "Hydrate generic content using your business context.",
        },
      ],
      columns: "2",
      variant: "accent",
      layout: "auth-grid",
    },
  },
  "features-3": {
    component: "Features",
    importPath: "@/sections/features/Features",
    schema: featuresSchema,
    displayName: "Features / Timeline",
    description: "Sequential feature storytelling for process-heavy products.",
    category: "content",
    family: "features",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #0f172a, #1e293b)",
    previewAccent: "#22d3ee",
    defaultProps: {
      kicker: "Implementation roadmap",
      heading: "Built for end-to-end delivery",
      subheading: "From architecture to deployment, each step is productized.",
      features: [
        {
          title: "Map structure",
          description: "Define reusable components and section contracts.",
        },
        {
          title: "Customize content",
          description: "Tune copy, visuals, and branding in a single workflow.",
        },
        {
          title: "Validate schema",
          description: "Strict data validation keeps generation safe.",
        },
        {
          title: "Export to code",
          description: "Push to starter and publish instantly.",
        },
      ],
      columns: "2",
      variant: "dark",
      layout: "timeline",
    },
  },
  "testimonials-1": {
    component: "Testimonials",
    importPath: "@/sections/testimonials/Testimonials",
    schema: testimonialSchema,
    displayName: "Testimonials / Classic",
    description: "Social proof section with quotes and ratings.",
    category: "social",
    family: "testimonials",
    template: "core",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    previewAccent: "#0f172a",
    defaultProps: {
      heading: "Loved by Thousands",
      subheading: "Don't just take our word for it.",
      testimonials: [
        {
          quote: "This changed how we build products.",
          name: "Sarah Kim",
          title: "CTO",
          company: "TechCorp",
          rating: 5,
        },
        {
          quote: "Incredibly intuitive and powerful.",
          name: "John Doe",
          title: "Founder",
          company: "StartupXYZ",
          rating: 5,
        },
      ],
      variant: "accent",
      layout: "cards",
    },
  },
  "testimonials-2": {
    component: "Testimonials",
    importPath: "@/sections/testimonials/Testimonials",
    schema: testimonialSchema,
    displayName: "Testimonials / Auth Slider",
    description:
      "Compact two-column testimonials inspired by authantimate style.",
    category: "social",
    family: "testimonials",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #eef2ff, #ddd6fe)",
    previewAccent: "#7c3aed",
    defaultProps: {
      kicker: "TESTIMONIALS",
      heading: "Client stories that build trust",
      subheading: "Hear from teams who launched faster with this workflow.",
      testimonials: [
        {
          quote: "We cut launch time from weeks to days.",
          name: "Aarav",
          title: "PM",
          company: "ScaleCo",
          rating: 5,
        },
        {
          quote: "The variant system helped us test ideas fast.",
          name: "Nitya",
          title: "Designer",
          company: "StudioLab",
          rating: 5,
        },
        {
          quote: "Generated code was clean and easy to maintain.",
          name: "Rohan",
          title: "Lead Dev",
          company: "BuildStack",
          rating: 5,
        },
      ],
      variant: "light",
      layout: "auth-slider",
    },
  },
  "testimonials-3": {
    component: "Testimonials",
    importPath: "@/sections/testimonials/Testimonials",
    schema: testimonialSchema,
    displayName: "Testimonials / Spotlight",
    description: "Highlight one marquee testimonial with supporting quotes.",
    category: "social",
    family: "testimonials",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #111827, #1f2937)",
    previewAccent: "#f59e0b",
    defaultProps: {
      kicker: "Trusted by ambitious teams",
      heading: "Results that speak for themselves",
      subheading: "A spotlight layout for high-impact social proof.",
      testimonials: [
        {
          quote: "This builder became our default launch workflow.",
          name: "Neha",
          title: "Founder",
          company: "LaunchDock",
          rating: 5,
        },
        {
          quote: "The design fidelity is shockingly good.",
          name: "Kabir",
          title: "Frontend Engineer",
          company: "PixelBox",
          rating: 5,
        },
        {
          quote: "Great balance of speed and structure.",
          name: "Pooja",
          title: "Product Manager",
          company: "Nexa",
          rating: 5,
        },
      ],
      variant: "dark",
      layout: "spotlight",
    },
  },
  "about-1": {
    component: "About",
    importPath: "@/sections/about/About",
    schema: aboutSchema,
    displayName: "About / Split",
    description: "Two-column about section with feature bullets.",
    category: "content",
    family: "about",
    template: "core",
    previewBackground: "linear-gradient(135deg, #f8fafc, #dbeafe)",
    previewAccent: "#2563eb",
    defaultProps: {
      badge: "About us",
      heading: "A complete solution for",
      highlight: "modern teams",
      description:
        "We help builders ship polished digital experiences with consistency and speed.",
      items: [
        {
          title: "Reusable Architecture",
          description: "Composable sections and strict schemas.",
        },
        {
          title: "Template Fidelity",
          description: "Preserve source-template design language.",
        },
      ],
      ctaText: "Know more",
      ctaHref: "#",
      layout: "split",
    },
  },
  "about-2": {
    component: "About",
    importPath: "@/sections/about/About",
    schema: aboutSchema,
    displayName: "About / AuthentiMATE",
    description: "Template-inspired about block with highlighted milestones.",
    category: "content",
    family: "about",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #eef2ff, #ffffff)",
    previewAccent: "#4f46e5",
    defaultProps: {
      badge: "New",
      heading: "SaaS boilerplate for",
      highlight: "high growth",
      description:
        "Launch your product pages with a system designed for real iteration.",
      items: [
        {
          title: "React + TypeScript",
          description: "Production-oriented defaults.",
        },
        {
          title: "AI-assisted copy",
          description: "Context-aware content hydration.",
        },
      ],
      ctaText: "Explore more",
      ctaHref: "#",
      layout: "authantimate",
    },
  },
  "about-3": {
    component: "About",
    importPath: "@/sections/about/About",
    schema: aboutSchema,
    displayName: "About / Stacked",
    description: "Centered heading with stacked capability cards.",
    category: "content",
    family: "about",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #111827, #312e81)",
    previewAccent: "#22d3ee",
    defaultProps: {
      badge: "Our process",
      heading: "Built for",
      highlight: "iterative teams",
      description:
        "A focused layout for concise storytelling and value highlights.",
      items: [
        {
          title: "Discover",
          description: "Map user journey and section architecture.",
        },
        {
          title: "Design",
          description: "Pick variants that align with your brand style.",
        },
        {
          title: "Deliver",
          description: "Export clean pages ready for deployment.",
        },
      ],
      layout: "stacked",
    },
  },
  "faq-1": {
    component: "FAQ",
    importPath: "@/sections/faq/FAQ",
    schema: faqSchema,
    displayName: "FAQ / Accordion",
    description: "Single-column accordion for common pre-sales questions.",
    category: "support",
    family: "faq",
    template: "core",
    previewBackground: "linear-gradient(135deg, #f8fafc, #f1f5f9)",
    previewAccent: "#334155",
    defaultProps: {
      kicker: "FAQ",
      heading: "Frequently Asked Questions",
      description: "Everything your users ask before they convert.",
      ctaText: "Contact support",
      ctaHref: "#",
      items: [
        {
          question: "Can I customize every section?",
          answer: "Yes, all section props are editable from the builder panel.",
        },
        {
          question: "Can I export production code?",
          answer:
            "Yes, generation creates a clean Vite project with your selected sections.",
        },
      ],
      layout: "accordion",
    },
  },
  "faq-2": {
    component: "FAQ",
    importPath: "@/sections/faq/FAQ",
    schema: faqSchema,
    displayName: "FAQ / AuthentiMATE",
    description: "Template-inspired FAQ with stronger visual hierarchy.",
    category: "support",
    family: "faq",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #eef2ff, #e0e7ff)",
    previewAccent: "#6366f1",
    defaultProps: {
      kicker: "OUR FAQS",
      heading: "Frequently Asked Questions",
      description: "Get clarity on onboarding, exports, and integrations.",
      ctaText: "Know More",
      ctaHref: "#",
      items: [
        {
          question: "How does AI hydration work?",
          answer:
            "The API uses your onboarding context and optional scraped source data to rewrite section copy.",
        },
        {
          question: "Will old projects still open?",
          answer:
            "Yes, existing section IDs remain valid and backward-compatible.",
        },
        {
          question: "Can I use my own assets?",
          answer:
            "Yes, image URLs can be updated per section from the property editor.",
        },
      ],
      layout: "authantimate",
    },
  },
  "faq-3": {
    component: "FAQ",
    importPath: "@/sections/faq/FAQ",
    schema: faqSchema,
    displayName: "FAQ / Two Column",
    description: "Split FAQ layout suitable for dense enterprise content.",
    category: "support",
    family: "faq",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #0f172a, #1e293b)",
    previewAccent: "#a78bfa",
    defaultProps: {
      kicker: "Knowledge base",
      heading: "Answers for scaling teams",
      description: "A denser FAQ format for deeper implementation topics.",
      items: [
        {
          question: "Can I add custom sections?",
          answer:
            "Yes, add a schema and component, then register a new section ID.",
        },
        {
          question: "How many sections can I export?",
          answer:
            "The default API schema currently allows up to 20 sections per page.",
        },
        {
          question: "Can I publish directly to GitHub?",
          answer:
            "Yes, configure owner/token and generate with repository push enabled.",
        },
        {
          question: "What stack is generated?",
          answer:
            "A Vite React app with shared section/ui source and generated page entry.",
        },
      ],
      layout: "two-column",
    },
  },
  "contact-1": {
    component: "Contact",
    importPath: "@/sections/contact/Contact",
    schema: contactSchema,
    displayName: "Contact / Panel",
    description: "Simple contact form block for conversion-oriented pages.",
    category: "support",
    family: "contact",
    template: "core",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    previewAccent: "#2563eb",
    defaultProps: {
      heading: "Send a message",
      description:
        "Tell us about your project and we will get back to you quickly.",
      primaryButtonText: "Send Message",
      consentText: "By submitting, you agree to our privacy policy.",
      layout: "panel",
    },
  },
  "contact-2": {
    component: "Contact",
    importPath: "@/sections/contact/Contact",
    schema: contactSchema,
    displayName: "Contact / Split",
    description: "Authentimate-inspired contact with details side panel.",
    category: "support",
    family: "contact",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #eef2ff, #f8fafc)",
    previewAccent: "#4f46e5",
    defaultProps: {
      heading: "Send a message",
      description:
        "We would love to hear from you. Fill out the form and we will reply within 24 hours.",
      address: "415, 4th Floor, Fortune 80 Building, University Road, Udaipur",
      email: "hello@authentimate.com",
      phone: "+91 98765 43210",
      primaryButtonText: "Send Message",
      consentText: "By clicking send, you agree to terms and cookie usage.",
      layout: "split",
    },
  },
  "contact-3": {
    component: "Contact",
    importPath: "@/sections/contact/Contact",
    schema: contactSchema,
    displayName: "Contact / Compact",
    description: "Compact contact module for tight landing page layouts.",
    category: "support",
    family: "contact",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #111827, #1f2937)",
    previewAccent: "#22d3ee",
    defaultProps: {
      heading: "Start your project",
      description: "Quick intro form for rapid qualification.",
      primaryButtonText: "Request Call",
      consentText: "I agree to receive updates and communication.",
      layout: "compact",
    },
  },
  "footer-1": {
    component: "Footer",
    importPath: "@/sections/footer/Footer",
    schema: footerSchema,
    displayName: "Footer / Classic",
    description: "Full footer with links, social icons, and copyright.",
    category: "layout",
    family: "footer",
    template: "core",
    previewBackground: "linear-gradient(135deg, #1e293b, #0f172a)",
    previewAccent: "#e2e8f0",
    defaultProps: {
      brandName: "My Brand",
      tagline: "Building the future, one commit at a time.",
      showYear: true,
      columns: [],
      socialLinks: [],
      variant: "dark",
      layout: "columns",
    },
  },
  "footer-2": {
    component: "Footer",
    importPath: "@/sections/footer/Footer",
    schema: footerSchema,
    displayName: "Footer / AuthentiMATE",
    description: "Template-style footer with newsletter and utility links.",
    category: "layout",
    family: "footer",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #ffffff, #eef2ff)",
    previewAccent: "#6366f1",
    defaultProps: {
      brandName: "AuthentiMATE",
      tagline: "Create, issue, and verify digital credentials with confidence.",
      showYear: true,
      columns: [
        {
          title: "Quick Links",
          links: [
            { label: "Home", href: "#" },
            { label: "Features", href: "#" },
            { label: "Pricing", href: "#" },
          ],
        },
        {
          title: "Support",
          links: [
            { label: "Company", href: "#" },
            { label: "Blog", href: "#" },
            { label: "Contact", href: "#" },
          ],
        },
      ],
      socialLinks: [
        { platform: "linkedin", href: "#" },
        { platform: "github", href: "#" },
      ],
      newsletterPlaceholder: "Email address",
      variant: "light",
      layout: "authantimate",
    },
  },
  "footer-3": {
    component: "Footer",
    importPath: "@/sections/footer/Footer",
    schema: footerSchema,
    displayName: "Footer / Minimal",
    description: "Slim brand-first footer for minimalist landing pages.",
    category: "layout",
    family: "footer",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #0b1020, #111827)",
    previewAccent: "#93c5fd",
    defaultProps: {
      brandName: "AuthentiMATE",
      tagline: "Trusted credential workflows.",
      showYear: true,
      columns: [],
      socialLinks: [],
      variant: "dark",
      layout: "minimal",
    },
  },
  "blitz-header": {
    component: "BlitzHeader",
    importPath: "@website-builder/sections",
    schema: blitzHeaderSchema,
    displayName: "Blitz / Header",
    description: "Minimal Next-style navigation with sticky blur and CTA.",
    category: "layout",
    family: "header",
    template: "blitz-clone",
    previewBackground: "#ffffff",
    previewAccent: "#111827",
    defaultProps: {
      logoUrl: "/images/blitz/assets-images/framerusercontent.com_images_RASesxV163EOQ4IVc0HISIG4r4.png",
      logoText: "Blitz",
      navLinks: [
        { label: "Home", href: "#" },
        { label: "Use Cases", href: "#usecases" },
        { label: "Pricing", href: "#pricing" },
        { label: "FAQ", href: "#faq" },
      ],
      ctaText: "Login",
      ctaHref: "#",
    },
  },
  "blitz-hero": {
    component: "BlitzHero",
    importPath: "@website-builder/sections",
    schema: blitzHeroSchema,
    displayName: "Blitz / Hero",
    description: "Centric high-impact hero with fadeUp animations and kicker text.",
    category: "conversion",
    family: "hero",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #eff6ff)",
    previewAccent: "#2563eb",
    defaultProps: {
      kicker: "The API for B2B Growth",
      title: "Target and enrich your ICP",
      subtitle: "Access 380M+ verified contacts and 60M+ companies via high-performance APIs. No lock-in, pay only for verified results.",
      primaryCTA: { text: "Get 1,000 credits free", href: "#signup" },
      secondaryCTA: { text: "API Reference", href: "#docs" },
      bottomNote: "Used by leading growth teams globally",
      highlightWord: "ICP",
      mockup: {
        labels: ["API Response", "Personas", "Companies", "Growth"],
        gridItems: ["98%", "60M+", "380M+", "API First"],
      },
    },
  },
  "blitz-brands": {
    component: "BlitzBrands",
    importPath: "@website-builder/sections",
    schema: blitzBrandsSchema,
    displayName: "Blitz / Brands",
    description: "Monochrome scrolling logo wall with animated logos.",
    category: "social",
    family: "header",
    template: "blitz-clone",
    previewBackground: "#ffffff",
    previewAccent: "#64748b",
    defaultProps: {
      title: "Powers some of the worlds most high-scale growth engines",
      logos: [
        { name: "Clay", src: "/images/blitz/assets-images/framerusercontent.com_images_KcdBGyZsJWdbdJVHndym4DRTtw.webp" },
        { name: "Make", src: "/images/blitz/assets-images/framerusercontent.com_images_by0K6v0Y3j2IM56ZMX7sTyuoXk.webp" },
        { name: "n8n", src: "/images/blitz/assets-images/framerusercontent.com_images_UTzLxaYnEZ4z37UUvAeUL03Y0o.png" },
        { name: "Throxy", src: "/images/blitz/assets-images/framerusercontent.com_images_NaGM8UmEZYtAB6VZv0Ylr54FQus.png" },
        { name: "Lead Expo", src: "/images/blitz/assets-images/framerusercontent.com_images_ZgF9VEl7cwBm5ks5XqGl0q4gIbs.png" },
        { name: "Databar.ai", src: "/images/blitz/assets-images/framerusercontent.com_images_PjC4jDuhfuksx9hUCrGaJ9kt240.png" },
        { name: "Solufinance", src: "/images/blitz/assets-images/framerusercontent.com_images_5e7roAEn2RheF7t3vlKCeRcZu3w.webp" },
        { name: "Growth Engine X", src: "/images/blitz/assets-images/framerusercontent.com_images_pTls0Enge50VTc2aDjTz9NP0Dg.png" },
      ],
    },
  },

  "blitz-features": {
    component: "BlitzFeatures",
    importPath: "@website-builder/sections",
    schema: blitzFeaturesSchema,
    displayName: "Blitz / Features",
    description: "Grid layout with icons and large visual mockups.",
    category: "content",
    family: "features",
    template: "blitz-clone",
    previewBackground: "#f9fafb",
    previewAccent: "#2563eb",
    defaultProps: {
      title: "Get unlimited B2B data",
      description: [
        "BlitzAPI transforms your GTM playbooks into automated, scalable workflows.",
        "Stop wasting credits on bad leads and outdated information. Integrate easily, pay only for results, and scale growth easily.",
      ],
      cta: { text: "Try it for free", href: "#signup" },
      featureCards: [
        { iconSrc: "/images/blitz/assets-images/framerusercontent.com_images_OVEMxKSDadrBYGTq6QtZsh8ceLQ.png", title: "API-first architecture" },
        { iconSrc: "/images/blitz/assets-images/framerusercontent.com_images_nBjEs1JX6H9at4KGO5uV0QHkIk.png", title: "Pay only for verified results" },
        { iconSrc: "/images/blitz/assets-images/framerusercontent.com_images_3KADvT0rewQNzigoYkisNRMzKI.png", title: "Built for Scalability & Reliability" },
        { iconSrc: "/images/blitz/assets-images/framerusercontent.com_images_RcumPqDYqoxUKGkIixltAdiGw.png", title: "Unlimited Growth Use-Cases" },
      ],
      visualImageSrc: "/images/blitz/assets-images/framerusercontent.com_images_wzWjxJPT1eMj66hrydpZX2uk.png",
      highlightWord: "unlimited",
    },
  },

  "blitz-use-cases": {
    component: "BlitzUseCases",
    importPath: "@website-builder/sections",
    schema: blitzUseCasesSchema,
    displayName: "Blitz / Use Cases",
    description: "Detailed use cases with interactive hover effects and profile mockups.",
    category: "content",
    family: "about",
    template: "blitz-clone",
    previewBackground: "#ffffff",
    previewAccent: "#2563eb",
    defaultProps: {
      title: "Your API teammate for any GTM workflow",
      useCases: [
        { icon: "🎯", title: "Top Quality B2B Data", desc: "Enrich, validate, and ship clean data into your workflows." },
        { icon: "📋", title: "Waterfall ICP", desc: "Prioritize by persona → Get only what matters, stop when quota is met." },
        { icon: "🔄", title: "Unlimited data enrichment", desc: "Enrich emails, phones, LinkedIn and company data — at scale, through simple API calls." },
      ],
      cta: { text: "Get 1,000 credits free", href: "#signup" },
      highlightWord: "API teammate",
    },
  },

  "blitz-integrations": {
    component: "BlitzIntegrations",
    importPath: "@website-builder/sections",
    schema: blitzIntegrationsSchema,
    displayName: "Blitz / Integrations",
    description: "Grid of technical integration partners with hover animations.",
    category: "content",
    family: "features",
    template: "blitz-clone",
    previewBackground: "#ffffff",
    previewAccent: "#111827",
    defaultProps: {
      title: "Seamless Integrations",
      subtitle: "Our platform plugs into your existing workflows — from no-code automations to enterprise stacks.",
      integrations: [
        { name: "Clay", src: "/images/blitz/assets-images/framerusercontent.com_images_KcdBGyZsJWdbdJVHndym4DRTtw.webp" },
        { name: "Make", src: "/images/blitz/assets-images/framerusercontent.com_images_by0K6v0Y3j2IM56ZMX7sTyuoXk.webp" },
        { name: "n8n", src: "/images/blitz/assets-images/framerusercontent.com_images_UTzLxaYnEZ4z37UUvAeUL03Y0o.png" },
        { name: "Databar", src: "/images/blitz/assets-images/framerusercontent.com_images_PjC4jDuhfuksx9hUCrGaJ9kt240.png" },
      ],
    },
  },

  "blitz-pricing": {
    component: "BlitzPricing",
    importPath: "@website-builder/sections",
    schema: blitzPricingSchema,
    displayName: "Blitz / Pricing Stats",
    description: "Dark dashboard with animated stats and cost comparison charts.",
    category: "conversion",
    family: "hero",
    template: "blitz-clone",
    previewBackground: "#0a0a0a",
    previewAccent: "#2563eb",
    defaultProps: {
      title: "Built to outperform. Priced to scale.",
      subtitle: "Our engine is not just another data provider. It's the infrastructure behind thousands of GTM workflows",
      stats: [
        { value: "+360M", label: "Verified B2B contacts, enriched and updated.", emoji: "👥" },
        { value: ">98%", label: "Email deliverability with real-time catch-all validation.", emoji: "📧" },
        { value: "+60M", label: "Enriched company profiles across all major markets.", emoji: "🏢" },
        { value: "96%", label: "Satisfaction rate from growth teams using our APIs daily.", emoji: "⭐" },
      ],
      highlightWord: "outperform",
      mockup: {
        labels: ["Contact Sync", "Lead Score", "Enrichment"],
      },
    },
  },

  "blitz-pricing-plans": {
    component: "BlitzPricingPlans",
    importPath: "@website-builder/sections",
    schema: blitzPricingPlansSchema,
    displayName: "Blitz / Pricing Plans",
    description: "Multiple subscription tiers with detailed feature lists and highlights.",
    category: "conversion",
    family: "hero",
    template: "blitz-clone",
    previewBackground: "#0a0a0a",
    previewAccent: "#2563eb",
    defaultProps: {
      title: "Cheaper, Better, Faster, Stronger",
      subtitle: "Access verified B2B data and enrichment tools at scraping cost. No hidden fees, no lock-in. Just clean, API-delivered results.",
      plans: [
        { name: "Unlimited Leads", price: "$399", period: "/month", desc: "For teams that need fresh company + people data, on repeat.", highlight: false, features: ["UNLIMITED Leads", "UNLIMITED Companies", "Access 380M+ contacts"], ctaText: "Get Started", ctaHref: "#signup" },
        { name: "Unlimited Email", price: "$499", period: "/month", desc: "For teams running cold email at scale.", highlight: true, badge: "Popular", features: ["Everything in Unlimited Leads", "UNLIMITED Email finder", "62M+ verified emails"], ctaText: "Get Started", ctaHref: "#signup" },
        { name: "Unlimited Phone", price: "$599", period: "/month", desc: "For high-output multi-channel teams.", highlight: false, features: ["Everything in Unlimited Email", "Unlimited Phone Numbers", "+40M Mobile Phone Numbers"], ctaText: "Get Started", ctaHref: "#signup" },
      ],
      highlightWord: "Stronger",
      footerNote: "Join leading companies who trust our platform to power their business.",
      footerLogos: ["classpass", "DocuSign", "Webflow", "codecademy"],
    },
  },

  "blitz-faq": {
    component: "BlitzFAQ",
    importPath: "@website-builder/sections",
    schema: blitzFAQSchema,
    displayName: "Blitz / FAQ",
    description: "Accordion-style FAQ block with smooth transitions.",
    category: "support",
    family: "faq",
    template: "blitz-clone",
    previewBackground: "#f8fafc",
    previewAccent: "#2563eb",
    defaultProps: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know about using our platform.",
      faqs: [
        { q: "What exactly is this platform?", a: "We provide high-performance B2B data APIs designed specifically for growth teams." },
        { q: "Is it GDPR compliant?", a: "Yes. We only surface business contact data from public sources and align with GDPR." },
      ],
    },
  },

  "blitz-cta": {
    component: "BlitzCTA",
    importPath: "@website-builder/sections",
    schema: blitzCTASchema,
    displayName: "Blitz / CTA",
    description: "Vibrant call-to-action banner with trust signals.",
    category: "conversion",
    family: "hero",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #1d4ed8, #3b82f6)",
    previewAccent: "#ffffff",
    defaultProps: {
      title: "Enterprise-grade targeting & enrichment at a scraping cost",
      subtitle: "Join thousands of GTM teams using our platform today.",
      cta: { text: "Get 1,000 credits free", href: "#signup" },
      benefits: [
        { icon: "⚡", label: "Blitz-fast APIs" },
        { icon: "🔒", label: "GDPR Compliant" },
        { icon: "💳", label: "No credit card" },
      ],
    },
  },

  "blitz-footer": {
    component: "BlitzFooter",
    importPath: "@website-builder/sections",
    schema: blitzFooterSchema,
    displayName: "Blitz / Footer",
    description: "Detailed brand footer with utility links and backdrop watermark.",
    category: "layout",
    family: "footer",
    template: "blitz-clone",
    previewBackground: "#0a0a0a",
    previewAccent: "#ffffff",
    defaultProps: {
      logoSrc: "/images/blitz/assets-images/framerusercontent.com_images_RASesxV163EOQ4IVc0HISIG4r4.png",
      brandName: "Brand",
      description: "The data engine behind high-performing GTM teams",
      copyright: "© 2025 Brand. All rights reserved.",
      links: {
        Product: ["Features", "Pricing", "Blog"],
        Legal: ["Terms", "Privacy"],
      },
      socialLinks: [
        { platform: "Youtube", href: "#", icon: "" },
        { platform: "LinkedIn", href: "#", icon: "" },
      ],
      watermark: "Brand",
    },
  },

  "blitz-features-old": {
    component: "Features",
    importPath: "@/sections/features/Features",
    schema: featuresSchema,
    displayName: "Blitz / Features (Generic)",
    description: "Feature block for use cases and product differentiation.",
    category: "content",
    family: "features",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    previewAccent: "#334155",
    defaultProps: {
      heading: "Built for modern teams",
      subheading: "Everything you need to explain the product quickly.",
      features: [
        {
          title: "Fast setup",
          description: "Start with a production-friendly shell.",
        },
        {
          title: "Flexible layout",
          description: "Choose the right section variant for the page.",
        },
        {
          title: "Clean export",
          description: "Generate focused code with only selected sections.",
        },
      ],
      columns: "3",
      variant: "light",
      layout: "cards",
    },
  },
  "blitz-testimonials-1": {
    component: "Testimonials",
    importPath: "@/sections/testimonials/Testimonials",
    schema: testimonialSchema,
    displayName: "Blitz / Testimonials",
    description: "Social proof block tuned for a minimalist SaaS page.",
    category: "social",
    family: "testimonials",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #dbeafe)",
    previewAccent: "#1d4ed8",
    defaultProps: {
      heading: "Teams trust the workflow",
      subheading: "Short, direct testimonials for the Blitz-style shell.",
      testimonials: [
        {
          quote: "We launched in a fraction of the time.",
          name: "Ava",
          title: "Founder",
          company: "Northstar",
          rating: 5,
        },
        {
          quote: "The builder felt fast and precise.",
          name: "Leo",
          title: "Engineer",
          company: "Orbit",
          rating: 5,
        },
      ],
      variant: "accent",
      layout: "cards",
    },
  },
  "blitz-footer-1": {
    component: "Footer",
    importPath: "@/sections/footer/Footer",
    schema: footerSchema,
    displayName: "Blitz / Footer",
    description: "Simple footer for the clone-style landing page.",
    category: "layout",
    family: "footer",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #0f172a, #1e293b)",
    previewAccent: "#e2e8f0",
    defaultProps: {
      brandName: "Blitz",
      tagline: "Fast launch pages for modern products.",
      showYear: true,
      columns: [
        {
          title: "Product",
          links: [
            { label: "Features", href: "#" },
            { label: "Use Cases", href: "#" },
          ],
        },
        {
          title: "Company",
          links: [
            { label: "About", href: "#" },
            { label: "Contact", href: "#" },
          ],
        },
      ],
      socialLinks: [],
      variant: "dark",
      layout: "columns",
    },
  },
  "cohort-header-1": {
    component: "Header",
    importPath: "@/sections/header/Header",
    schema: headerSchema,
    displayName: "Web Cohort / Header",
    description: "Program-style header for cohort and course landing pages.",
    category: "layout",
    family: "header",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #111827, #1e293b)",
    previewAccent: "#f59e0b",
    defaultProps: {
      title: "Web Cohort",
      subtitle: "Master modern product delivery",
      showCTA: true,
      ctaText: "Join Now",
      ctaHref: "#",
      variant: "dark",
      layout: "auth-glass",
      navLinks: [
        { label: "About", href: "#" },
        { label: "Curriculum", href: "#" },
        { label: "Speakers", href: "#" },
        { label: "FAQ", href: "#" },
      ],
    },
  },
  "cohort-hero-1": {
    component: "Hero",
    importPath: "@/sections/hero/Hero",
    schema: heroSchema,
    displayName: "Web Cohort / Hero",
    description:
      "Educational hero with a stronger course-style value proposition.",
    category: "conversion",
    family: "hero",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #0f172a, #312e81)",
    previewAccent: "#f8fafc",
    defaultProps: {
      kicker: "Learn by building",
      headline: "Become the engineer your team needs",
      description:
        "A course landing page hero with strong hierarchy and conversion focus.",
      primaryCTAText: "Enroll Now",
      primaryCTAHref: "#",
      secondaryCTAText: "View Curriculum",
      secondaryCTAHref: "#",
      backgroundStyle: "gradient",
      align: "left",
      layout: "split-card",
    },
  },
  "cohort-features-1": {
    component: "Features",
    importPath: "@/sections/features/Features",
    schema: featuresSchema,
    displayName: "Web Cohort / Benefits",
    description: "Benefit-led feature block for cohort value points.",
    category: "content",
    family: "features",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e0f2fe)",
    previewAccent: "#0ea5e9",
    defaultProps: {
      kicker: "What you get",
      heading: "A curriculum built for real projects",
      subheading:
        "The structure is focused on delivery, practice, and confidence.",
      features: [
        {
          title: "Live projects",
          description: "Work on practical assignments.",
        },
        {
          title: "Mentor guidance",
          description: "Get feedback as you progress.",
        },
        {
          title: "Portfolio outcomes",
          description: "Graduate with tangible work.",
        },
      ],
      columns: "3",
      variant: "light",
      layout: "cards",
    },
  },
  "cohort-testimonials-1": {
    component: "Testimonials",
    importPath: "@/sections/testimonials/Testimonials",
    schema: testimonialSchema,
    displayName: "Web Cohort / Testimonials",
    description: "Student and alumni proof for the course landing page.",
    category: "social",
    family: "testimonials",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #111827, #0f172a)",
    previewAccent: "#38bdf8",
    defaultProps: {
      kicker: "Student stories",
      heading: "Built by learners, backed by results",
      subheading: "Course-style testimonials with a stronger narrative tone.",
      testimonials: [
        {
          quote: "I shipped my first project in two weeks.",
          name: "Meera",
          title: "Student",
          company: "Web Cohort",
          rating: 5,
        },
        {
          quote: "The structure made a huge difference.",
          name: "Arjun",
          title: "Developer",
          company: "Web Cohort",
          rating: 5,
        },
      ],
      variant: "dark",
      layout: "spotlight",
    },
  },
  "cohort-footer-1": {
    component: "Footer",
    importPath: "@/sections/footer/Footer",
    schema: footerSchema,
    displayName: "Web Cohort / Footer",
    description: "Course footer with supportive links and newsletter language.",
    category: "layout",
    family: "footer",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #0f172a, #111827)",
    previewAccent: "#38bdf8",
    defaultProps: {
      brandName: "Web Cohort",
      tagline: "A hands-on path to shipping better web products.",
      showYear: true,
      columns: [
        {
          title: "Program",
          links: [
            { label: "Curriculum", href: "#" },
            { label: "Speakers", href: "#" },
          ],
        },
        {
          title: "Support",
          links: [
            { label: "FAQ", href: "#" },
            { label: "Contact", href: "#" },
          ],
        },
      ],
      socialLinks: [],
      variant: "dark",
      layout: "columns",
    },
  },
  "blitz-about-1": {
    component: "About",
    importPath: "@/sections/about/About",
    schema: aboutSchema,
    displayName: "Blitz / About",
    description:
      "Two-column about section aligned with Blitz-style product copy.",
    category: "content",
    family: "about",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e0e7ff)",
    previewAccent: "#4338ca",
    defaultProps: {
      badge: "Why Blitz",
      heading: "Designed for",
      highlight: "fast-moving teams",
      description:
        "A concise product story block with clear value cards and visual contrast.",
      items: [
        {
          title: "Clean structure",
          description: "Readable layout for fast scanning.",
        },
        {
          title: "Product-first copy",
          description: "Short sections with strong hierarchy.",
        },
      ],
      ctaText: "Read the story",
      ctaHref: "#",
      layout: "blitz-clone",
    },
  },
  "blitz-faq-1": {
    component: "FAQ",
    importPath: "@/sections/faq/FAQ",
    schema: faqSchema,
    displayName: "Blitz / FAQ",
    description: "Direct FAQ layout with compact cards for product objections.",
    category: "support",
    family: "faq",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    previewAccent: "#334155",
    defaultProps: {
      kicker: "Questions",
      heading: "Need more clarity?",
      description: "Quick answers before users start your product.",
      items: [
        {
          question: "Can we customize sections?",
          answer: "Yes, props can be edited from the builder panel.",
        },
        {
          question: "Do we export only selected sections?",
          answer: "Yes, generation includes only configured section instances.",
        },
        {
          question: "Will this work with Blitz shell?",
          answer: "Yes, choose the Blitz template shell during export.",
        },
      ],
      layout: "blitz-clone",
    },
  },
  "blitz-contact-1": {
    component: "Contact",
    importPath: "@/sections/contact/Contact",
    schema: contactSchema,
    displayName: "Blitz / Contact",
    description:
      "Conversion-focused contact section with clean form hierarchy.",
    category: "support",
    family: "contact",
    template: "blitz-clone",
    previewBackground: "linear-gradient(135deg, #f8fafc, #eef2ff)",
    previewAccent: "#4f46e5",
    defaultProps: {
      heading: "Talk to our team",
      description: "Share your goals and we will get back with a focused plan.",
      primaryButtonText: "Send Message",
      consentText: "By sending this form, you agree to our privacy terms.",
      layout: "blitz-clone",
    },
  },
  "cohort-about-1": {
    component: "About",
    importPath: "@/sections/about/About",
    schema: aboutSchema,
    displayName: "Web Cohort / About",
    description:
      "Program-style about section with outcomes and mentorship narrative.",
    category: "content",
    family: "about",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #0f172a, #1e293b)",
    previewAccent: "#38bdf8",
    defaultProps: {
      badge: "About the program",
      heading: "Built for",
      highlight: "career acceleration",
      description:
        "A structured section for curriculum outcomes, mentoring support, and delivery model.",
      items: [
        {
          title: "Hands-on projects",
          description: "Build portfolio-ready applications.",
        },
        {
          title: "Mentor reviews",
          description: "Weekly guidance from experienced engineers.",
        },
        {
          title: "Career prep",
          description: "Interview workflows and communication support.",
        },
      ],
      ctaText: "See outcomes",
      ctaHref: "#",
      layout: "web-cohort",
    },
  },
  "cohort-faq-1": {
    component: "FAQ",
    importPath: "@/sections/faq/FAQ",
    schema: faqSchema,
    displayName: "Web Cohort / FAQ",
    description: "Dark FAQ variant for cohort and course pages.",
    category: "support",
    family: "faq",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #111827, #0f172a)",
    previewAccent: "#38bdf8",
    defaultProps: {
      kicker: "Program FAQ",
      heading: "Everything about the cohort",
      description: "Start dates, mentoring model, and expected outcomes.",
      items: [
        {
          question: "Is this beginner-friendly?",
          answer:
            "The program is designed for motivated learners with foundational web basics.",
        },
        {
          question: "How much time per week?",
          answer: "Most participants spend 8-12 focused hours weekly.",
        },
        {
          question: "Will I build real projects?",
          answer: "Yes, each module ships tangible project outcomes.",
        },
      ],
      layout: "web-cohort",
    },
  },
  "cohort-contact-1": {
    component: "Contact",
    importPath: "@/sections/contact/Contact",
    schema: contactSchema,
    displayName: "Web Cohort / Contact",
    description: "Dark contact section with admission-focused messaging.",
    category: "support",
    family: "contact",
    template: "web-cohort",
    previewBackground: "linear-gradient(135deg, #0f172a, #111827)",
    previewAccent: "#38bdf8",
    defaultProps: {
      heading: "Talk to admissions",
      description: "Share your goals and we will guide the right cohort track.",
      address: "Online + mentor-led sessions",
      email: "admissions@webcohort.dev",
      phone: "+91 90000 12345",
      primaryButtonText: "Apply Now",
      consentText:
        "I agree to receive admission updates and cohort information.",
      layout: "web-cohort",
    },
  },

  // ─── Web-Cohort Template Sections ──────────────────────────────────────────
  "cohort-header": {
    component: "WebCohortHeader",
    importPath: "@website-builder/sections",
    schema: webCohortHeaderSchema,
    displayName: "Cohort / Header",
    description: "Sticky glassmorphism header with logo and single navigation link.",
    category: "layout",
    family: "header",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      logoUrl: "/images/web-cohort/CreativeLogo.png",
      ctaText: "Join Now",
      navLinks: [{ label: "Know More", href: "#curriculum" }],
    },
  },
  "cohort-hero": {
    component: "WebCohortHero",
    importPath: "@website-builder/sections",
    schema: webCohortHeroSchema,
    displayName: "Cohort / Hero",
    description: "High-impact hero with video, stats, and value props.",
    category: "conversion",
    family: "hero",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      chipText: "Struggling for Internships to Job Ready in 6 Months",
      title: [
        { text: "Course", highlight: true },
        { text: " Knowledge ≠ ", highlight: false },
        { text: "Job", highlight: true },
        { text: " Readiness. We Make You Job Ready ", highlight: false },
        { text: "Developer", highlight: true },
        { text: ".", highlight: false }
      ],
      subtitle: "Tired of courses that promise skills but don’t deliver real world job skills? Build production-ready apps alongside best practices from industry grade developers.",
      joinedCount: 400,
      joinedText: "developers already in queue, Join the Waitlist",
      emailPlaceholder: "Enter your email",
      emailCta: "Join the Waitlist",
      video: {
        title: "Myth-Busting Truths for Developers",
        subtitle: "Watch real developers share their transformation journey from struggling with internships to landing their dream jobs",
        wistiaVideoId: "oqxvk0siq4",
      },
      valueProps: [
        { 
          title: "73% of developers build identical portfolio projects which gets rejected", 
          description: "Youtube clone, weather app, to-do list, If these are your projects, Forget jobs, you won’t land an internship.",
          type: "carousel",
          carouselItems: [
            { title: "Conversational AI Recruiter", description: "AI agent that conducts job interviews, scores candidates, and gives real-time behavioral insights." },
            { title: "Automated AI Sales Agent", description: "AI sales agents that engage leads, handle objections, and close deals—24/7." },
            { title: "Omnichannel Comment Engine", description: "AI tool that auto-generates personalized, context-aware comments to boost engagement." }
          ]
        },
        {
          title: "Not just another course, Its a Experiential cohort",
          description: "No bluff. No more scattered learning or random tutorials. This is a hands-on developer journey.",
          type: "tech-stack",
          items: ["Next.js", "TypeScript", "Redis", "Postgres", "Redis", "Docker"]
        },
        {
          title: "Approach Development",
          description: "Learn how to think like a senior engineer and solve complex problems.",
          type: "default"
        },
        {
          title: "Master E2E Dev",
          description: "Go from zero to full-stack deployment with confidence.",
          type: "default"
        }
      ]
    },
  },
  "cohort-benefits": {
    component: "WebCohortBenefits",
    importPath: "@website-builder/sections",
    schema: webCohortBenefitsSchema,
    displayName: "Cohort / Benefits",
    description: "Animated grid of program benefits and core value points.",
    category: "content",
    family: "features",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [{ text: "What You Will Get", highlight: false }],
      benefits: [
        { title: "Production Grade Projects", description: "Build real products like AI recruiters and sales agents.", icon: "rocket" },
        { title: "Industry Mentorship", description: "Learn from developers at top tech companies.", icon: "users" },
      ],
    },
  },
  "cohort-curriculum": {
    component: "WebCohortCurriculum",
    importPath: "@website-builder/sections",
    schema: webCohortCurriculumSchema,
    displayName: "Cohort / Curriculum",
    description: "Detailed course modules with interactive phases and perks.",
    category: "content",
    family: "features",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [
        { text: "Our Cohort Includes What ", highlight: false },
        { text: "Real Developers", highlight: true },
        { text: " Actually Use", highlight: false }
      ],
      subtitle: "No outdated frameworks or toy projects. Master exact tools and practices powering today's top teams.",
      modules: [
        { title: "Creative Fullstack Mastery", duration: "Phase 1", lessons: ["Modern Frontend & Backend Systems", "Building Industry Grade Products", "High Precision Design & Motion"] },
        { title: "Generative AI Agent Systems", duration: "Phase 2", lessons: ["Building Production-Grade AI Agents", "Multi-Agent Orchestration", "Deployment & Scaling AI Systems"] },
        { title: "System Design & Scaling", duration: "Phase 3", lessons: ["Architecting for Millions", "Performance Optimization", "Advanced Security Patterns"] },
      ],
      perks: [
        "✨ Lifetime access to course materials",
        "👥 Direct mentorship from industry experts",
        "🏆 Certificate of completion",
        "💼 Job placement assistance",
        "🌐 Access to exclusive developer community",
        "📚 Bonus resources and advanced tutorials",
      ]
    },
  },
  "cohort-speakers": {
    component: "WebCohortSpeakers",
    importPath: "@website-builder/sections",
    schema: webCohortSpeakersSchema,
    displayName: "Cohort / Speakers",
    description: "Grid of industry guest speakers and mentors.",
    category: "social",
    family: "testimonials",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [{ text: "Step Into The Real World With Industry Mentors", highlight: false }],
      subtitle: "Stop learning from tutorials. Start learning from engineers who build production systems for millions of users.",
      speakers: [
        { id: "1", name: "Aman Minhas", designation: "Tech Lead at Nas Company", profilePhoto: "/images/web-cohort/speakers/guest01.jpeg", linkedinUrl: "#" },
        { id: "2", name: "Ashish Aryan", designation: "Senior Software Engineer at Velotio", profilePhoto: "/images/web-cohort/speakers/guest02.jpeg", linkedinUrl: "#" },
        { id: "3", name: "Dinansh Bhardwaj", designation: "Senior Backend Engineer at Webanix", profilePhoto: "/images/web-cohort/speakers/guest03.jpeg", linkedinUrl: "#" },
        { id: "4", name: "Madhav Khandal", designation: "Product Designer at Zoconut", profilePhoto: "/images/web-cohort/speakers/guest04.jpeg", linkedinUrl: "#" },
      ],
    },
  },
  "cohort-why-us": {
    component: "WebCohortWhyUs",
    importPath: "@website-builder/sections",
    schema: webCohortWhyUsSchema,
    displayName: "Cohort / Why Us",
    description: "Comparison section showing why this cohort is better than generic learning.",
    category: "content",
    family: "about",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [{ text: "Creative Upaay Vs. The Rest", highlight: false }],
      subtitle: "We’ve crafted an experience that breaks away from the usual.",
      othersPoints: ["YouTube tutorials", "Generic projects"],
      ourPoints: ["Hands-on mentorship", "Real-world products"],
    },
  },
  "cohort-note": {
    component: "WebCohortNote",
    importPath: "@website-builder/sections",
    schema: webCohortNoteSchema,
    displayName: "Cohort / CEO Note",
    description: "Personal inspirational note from the CEO with CTA.",
    category: "conversion",
    family: "hero",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [{ text: "This is a hands-on, live experience designed to help you find your voice...", highlight: false }],
      chipText: "Note From CEO",
      ctaText: "Join the Waitlist",
    },
  },
  "cohort-testimonials": {
    component: "WebCohortTestimonials",
    importPath: "@website-builder/sections",
    schema: webCohortTestimonialsSchema,
    displayName: "Cohort / Testimonials",
    description: "Authentic student success stories with a strong narrative tone.",
    category: "social",
    family: "testimonials",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [
        { text: "From ", highlight: false },
        { text: "Developers ", highlight: true },
        { text: "Who Were Once Where You Are", highlight: false }
      ],
      subtitle: "Honest stories from developers who went from rejected applications to dream job offers.",
      testimonials: [
        { id: "1", name: "Paraj Jain", testimonialText: "Creative Cohort join kiya aur 6 months mein real-time collaboration platform build kiya jo actually 5000+ users use karte hain daily.", rating: 5, profilePhoto: "/images/web-cohort/testimonial01.jpeg" },
        { id: "2", name: "Ashmita", testimonialText: "When I deployed it live and showed real user analytics in interviews, recruiters stopped scrolling and started asking technical questions.", rating: 5, profilePhoto: "/images/web-cohort/testimonial02.jpeg" },
        { id: "3", name: "Daksh", testimonialText: "Creative Cohort taught me to make AI my coding assistant instead. My interviewer said 'Finally, someone who understands both AI and scalable systems.'", rating: 5, profilePhoto: "/images/web-cohort/testimonial03.jpeg" },
      ],
    },
  },
  "cohort-faq": {
    component: "WebCohortFAQ",
    importPath: "@website-builder/sections",
    schema: webCohortFAQSchema,
    displayName: "Cohort / FAQ",
    description: "Dark, detailed FAQ accordion section.",
    category: "support",
    family: "faq",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [
        { text: "Got Questions? We've Got Answers", highlight: false }
      ],
      subtitle: "Find answers to the most common questions about our Creative Cohort program. Still have questions? Feel free to reach out!",
      faqs: [
        { id: "1", question: "Is this suitable for someone with no coding background?", answer: "This cohort is designed for developers who already understand coding fundamentals but struggle with real-world application." },
        { id: "2", question: "How is this different from other bootcamps?", answer: "Most bootcamps teach you to follow tutorials. We train you the way we train our internal development teams." },
        { id: "3", question: "What tech stack will I learn?", answer: "You'll master React with TypeScript, Next.js, Node.js, PostgreSQL, Redis, and AWS." },
        { id: "4", question: "What if AI replaces developers?", answer: "We don't teach you to fear AI - we teach you to leverage it as your coding assistant." },
      ],
    },
  },
  "cohort-footer": {
    component: "WebCohortFooter",
    importPath: "@website-builder/sections",
    schema: webCohortFooterSchema,
    displayName: "Cohort / Footer",
    description: "Call-to-action focused footer with contact community links.",
    category: "layout",
    family: "footer",
    template: "web-cohort",
    previewBackground: "#000000",
    previewAccent: "#CB97FF",
    defaultProps: {
      title: [
        { text: "Ready to Transform Your Creative Journey?", highlight: false }
      ],
      subtitle: "Join our creative cohort and start your journey from beginner to confident developer and storyteller.",
      logoUrl: "/images/web-cohort/CreativeLogo.png",
      email: "cohort@creativeupaay.com",
      phone: "+91-8118855738",
      whatsappNumber: "+91-8118855738",
      whatsappLink: "https://chat.whatsapp.com/KPjM1bvf6BYAUiGc1RpJb5",
      copyright: "© Creative Upaay 2025",
    },
  },
  "cohort-whatsapp": {
    component: "WebCohortWhatsAppFloat",
    importPath: "@website-builder/sections",
    schema: webCohortWhatsAppFloatSchema,
    displayName: "Cohort / WhatsApp Float",
    description: "Floating WhatsApp button for community access.",
    category: "support",
    family: "contact",
    template: "web-cohort",
    previewBackground: "#000",
    previewAccent: "#25D366",
    defaultProps: {
      whatsappLink: "https://chat.whatsapp.com/KPjM1bvf6BYAUiGc1RpJb5",
    },
  },

  // ─── Authantimate Template Sections ────────────────────────────────────────
  // These are the dedicated 1:1 ports from the authantimate dummy template.
  // They are rendered by AuthHeader, AuthHero, etc. from @website-builder/sections.

  "auth-header": {
    component: "AuthHeader",
    importPath: "@website-builder/sections",
    schema: headerSchema,
    displayName: "Authantimate / Header",
    description: "Fixed top navigation with logo text, nav links, and CTA button.",
    category: "layout",
    family: "header",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      logoText: "Solid",
      navLinks: [
        { label: "Home", href: "#" },
        { label: "Features", href: "#features" },
        { label: "FAQ", href: "#faq" },
        { label: "Support", href: "#support" },
      ],
      ctaText: "Get Pro 🔥",
      ctaHref: "#",
    },
  },

  "auth-hero": {
    component: "AuthHero",
    importPath: "@website-builder/sections",
    schema: heroSchema,
    displayName: "Authantimate / Hero",
    description: "Left-aligned hero with email capture, headline highlight, and product screenshot.",
    category: "conversion",
    family: "hero",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #f8fafc, #EDF5FF)",
    previewAccent: "#006BFF",
    defaultProps: {
      kicker: "🔥 Certify Smarter, Not Harder",
      headline: "Digital Certificates Made",
      headlineHighlight: "Easy",
      description: "Say goodbye to manual processes! Simplify creating, managing, and verifying digital certificates for individuals and organizations alike.",
      emailPlaceholder: "Enter your email address",
      ctaText: "Get Early Access",
      ctaHref: "#",
      trustNote: "Try for free — no credit card required.",
      imageUrl: "",
    },
  },

  "auth-brands": {
    component: "AuthBrands",
    importPath: "@website-builder/sections",
    schema: brandsSchema,
    displayName: "Authantimate / Brands",
    description: "Trusted-by logo strip shown beneath the hero.",
    category: "social",
    family: "header",
    template: "authantimate",
    previewBackground: "#F8F9FF",
    previewAccent: "#006BFF",
    defaultProps: {
      logos: [
        { name: "Google", imageUrl: "" },
        { name: "Microsoft", imageUrl: "" },
        { name: "LinkedIn", imageUrl: "" },
        { name: "Udemy", imageUrl: "" },
        { name: "Coursera", imageUrl: "" },
      ],
    },
  },

  "auth-features": {
    component: "AuthFeatures",
    importPath: "@website-builder/sections",
    schema: featuresSchema,
    displayName: "Authantimate / Features",
    description: "3-column feature card grid with icons and animated entrance.",
    category: "content",
    family: "features",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      kicker: "SOLID FEATURES",
      title: "What Sets Us Apart",
      description: "From creation to verification, we've got you covered. Discover features designed for simplicity and success.",
      items: [
        { icon: "", title: "Bulk Issuance", description: "Streamline the process of issuing certificates and badges, especially when handling large quantities." },
        { icon: "", title: "QR & URL Certificates", description: "Generate certificates with unique URLs and QR codes for easy verification and sharing." },
        { icon: "", title: "Digital Locker Storage", description: "Store certificates securely in a digital locker for easy access and management." },
        { icon: "", title: "Easy Sharing", description: "Enable recipients to share their certificates on social media effortlessly." },
        { icon: "", title: "Analytics & Tracking", description: "Gain insights into how and where credentials are being used." },
      ],
    },
  },

  "auth-about": {
    component: "AuthAbout",
    importPath: "@website-builder/sections",
    schema: aboutSchema,
    displayName: "Authantimate / About",
    description: "Two-block split layout with numbered milestones and integrations sub-section.",
    category: "content",
    family: "about",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      badge: "New",
      badgeLabel: "SaaS Boilerplate for Next.js",
      heading: "A Complete Solution for",
      headingHighlight: "SaaS Startup",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies lacus non fermentum ultrices.",
      items: [
        { number: "01", title: "React 18, Next.js 13 and TypeScript", description: "Production-oriented defaults." },
        { number: "02", title: "Fully Customizable", description: "Every prop is schema-driven and hydrated." },
      ],
      imageUrl: "",
      section2Kicker: "Launch Your SaaS Fast",
      section2Heading: "Packed with All Essential",
      section2Highlight: "Integrations",
      section2Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies lacus non fermentum ultrices.",
      ctaText: "Know More",
      ctaHref: "#",
      image2Url: "",
    },
  },

  "auth-cta": {
    component: "AuthCTA",
    importPath: "@website-builder/sections",
    schema: ctaSchema,
    displayName: "Authantimate / CTA",
    description: "Gradient call-to-action banner with decorative image and join button.",
    category: "conversion",
    family: "hero",
    template: "authantimate",
    previewBackground: "linear-gradient(135deg, #F8F9FF, #DEE7FF)",
    previewAccent: "#181C31",
    defaultProps: {
      heading: "Join Us Today and Transform Your Certificate Management",
      description: "Experience the power of digital certificates, secure verification, and seamless sharing. Get started now!",
      ctaText: "Join Now",
      ctaHref: "#",
      imageUrl: "",
    },
  },

  "auth-faq": {
    component: "AuthFAQ",
    importPath: "@website-builder/sections",
    schema: faqSchema,
    displayName: "Authantimate / FAQ",
    description: "Split-panel FAQ with accordion answers and a side CTA link.",
    category: "support",
    family: "faq",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      kicker: "OUR FAQS",
      heading: "Frequently Asked",
      headingHighlight: "Questions",
      ctaText: "Know More",
      ctaHref: "#",
      items: [
        { question: "How does the certificate issuance process work?", answer: "You can easily create and issue digital certificates in bulk by uploading participant details via an Excel sheet." },
        { question: "How can certificates be verified?", answer: "Users or third parties can scan the QR code on the certificate to instantly validate it via our secure web portal." },
        { question: "Can certificates be shared on social media?", answer: "Yes, recipients can share their digital certificates on platforms like LinkedIn, Facebook, and Twitter." },
      ],
    },
  },

  "auth-testimonial": {
    component: "AuthTestimonial",
    importPath: "@website-builder/sections",
    schema: testimonialSchema,
    displayName: "Authantimate / Testimonials",
    description: "2-column testimonial grid with star ratings and avatar initials.",
    category: "social",
    family: "testimonials",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      kicker: "TESTIMONIALS",
      title: "Client's Testimonials",
      description: "Hear from those who've experienced the benefits of our solutions.",
      items: [
        { name: "Dr P.K. Singh", designation: "Dean CTAE Udaipur", avatar: "", content: "Authentimate has streamlined our certificate issuance at our Tech Fest. It's efficient, reliable, and easy to use." },
        { name: "Anuj Kanwar", designation: "Founder Schoolsharks", avatar: "", content: "Authentimate has greatly enhanced our certificate management. Its verification ensures authenticity." },
        { name: "Sourabh Goyal", designation: "Founder SuccessBrew", avatar: "", content: "Authentimate has transformed how we issue and verify certificates. The ease of distribution makes it reliable." },
        { name: "Dillesh Kumar", designation: "Founder CareerGeek", avatar: "", content: "Authentimate has simplified the process of issuing certificates. It's fast, secure, and makes sharing effortless." },
      ],
    },
  },

  "auth-pricing": {
    component: "AuthPricing",
    importPath: "@website-builder/sections",
    schema: pricingSchema,
    displayName: "Authantimate / Pricing",
    description: "3-tier pricing table with popular badge, feature lists, and CTA.",
    category: "conversion",
    family: "hero",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      kicker: "PRICING PLANS",
      title: "Flexible Pricing",
      description: "We offer flexible pricing options tailored to your needs.",
      ctaText: "Contact Now",
      ctaHref: "#",
      plans: [
        { price: "$10", period: "/month", name: "Small Pack", description: "Perfect for small teams.", features: ["300 GB Storage", "Unlimited Photos and Videos", "Exclusive Support"], isPopular: false },
        { price: "$59", period: "/month", name: "Medium Pack", description: "Great for growing orgs.", features: ["300 GB Storage", "Unlimited Photos and Videos", "Exclusive Support", "Custom Branding Strategy"], isPopular: true },
        { price: "$189", period: "/month", name: "Large Pack", description: "Enterprise-grade.", features: ["300 GB Storage", "Unlimited Photos and Videos", "Exclusive Support", "Custom Branding Strategy"], isPopular: false },
      ],
    },
  },

  "auth-contact": {
    component: "AuthContact",
    importPath: "@website-builder/sections",
    schema: contactSchema,
    displayName: "Authantimate / Contact",
    description: "Split contact form with address, email, and phone info panel.",
    category: "support",
    family: "contact",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      heading: "Send a message",
      address: "415, 4th Floor, Fortune 80 Building, University Road, Udaipur, Rajasthan - 313001",
      email: "yourmail@domainname.com",
      phone: "+009 42334 6343 843",
      primaryButtonText: "Send Message",
      consentText: `By clicking Checkbox, you agree to use our "Form" terms and consent cookie usage in browser.`,
    },
  },

  "auth-footer": {
    component: "AuthFooter",
    importPath: "@website-builder/sections",
    schema: footerSchema,
    displayName: "Authantimate / Footer",
    description: "Full-width footer with brand column, quick links, support links, and newsletter.",
    category: "layout",
    family: "footer",
    template: "authantimate",
    previewBackground: "#ffffff",
    previewAccent: "#006BFF",
    defaultProps: {
      brandName: "Solid",
      tagline: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      contactEmail: "hello@solid.com",
      quickLinks: [
        { label: "Home", href: "#" },
        { label: "Product", href: "#" },
        { label: "Careers", href: "#" },
        { label: "Pricing", href: "#" },
      ],
      supportLinks: [
        { label: "Company", href: "#" },
        { label: "Press media", href: "#" },
        { label: "Our Blog", href: "#" },
        { label: "Contact Us", href: "#" },
      ],
      newsletterPlaceholder: "Email address",
      copyright: `© ${new Date().getFullYear()} Solid. All rights reserved`,
    },
  },
};

export const ALLOWED_SECTION_TYPES = Object.keys(registry) as Array<
  keyof typeof registry
>;
