import { getComponent } from "@website-builder/registry";

interface ValidatedSection {
  type: string;
  props: Record<string, unknown>;
}

/**
 * Generates the /src/pages/index.tsx content for the target project.
 * Only accepts scalar prop values — no arbitrary expressions.
 */
export function generatePage(sections: ValidatedSection[]): string {
  const imports = new Set<string>();
  const jsxLines: string[] = [];

  for (const section of sections) {
    const entry = getComponent(section.type);

    // Build the import statement using the registry importPath
    imports.add(`import { ${entry.component} } from "${entry.importPath}";`);

    // Serialize props — only string | number | boolean | array | plain object (no functions, no JSX)
    const propsStr = serializeProps(section.props);
    jsxLines.push(`      <${entry.component} ${propsStr} />`);
  }

  return [
    "// Auto-generated by Website Builder v2 — do not edit manually",
    "// Re-generate via: POST /generate",
    "",
    ...Array.from(imports),
    "",
    "export default function Page() {",
    "  return (",
    "    <>",
    ...jsxLines,
    "    </>",
    "  );",
    "}",
    "",
  ].join("\n");
}

// ─── Prop serializer ──────────────────────────────────────────────────────────

/**
 * Converts a props record to a JSX attribute string.
 * Strings → `key="value"`, everything else → `key={JSON.stringify(value)}`
 * Arrays and objects are JSON-serialized safely.
 * No expressions, no function refs, no user-supplied code.
 */
function serializeProps(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([, v]) => v !== undefined && v !== null)
    .map(([key, value]) => {
      if (typeof value === "string") {
        // Escape double quotes in strings
        const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        return `${key}="${escaped}"`;
      }
      // boolean, number, array, object → JSON — no expressions
      return `${key}={${JSON.stringify(value)}}`;
    })
    .join(" ");
}
