// This file is generated by Website Builder v2. Do not edit manually.
// Re-generate by running: POST /generate with your page config.

export default function Page() {
  return (
    <div style={{ textAlign: "center", padding: "96px 24px", fontFamily: "var(--font-family, sans-serif)" }}>
      <h1 style={{ fontSize: "2.5rem", fontWeight: 800, color: "var(--color-primary, #1a1a2e)" }}>
        🚀 Your website is ready
      </h1>
      <p style={{ color: "var(--color-muted, #64748b)", marginTop: "16px" }}>
        Use the Website Builder to configure your sections and regenerate this file.
      </p>
    </div>
  );
}
